// SPDX-License-Identifier: Apache-2.0
// French. Phrases are lowercase and unaccented (labels are normalised before matching)
// except `dates.ongoing`, which is matched against the raw, lowercased date text.
//
// The shape of a pack is documented in `_template.js`; every key must exist in
// `src/schema/fields.js`, which the build checks.

export default {
  lang: 'fr',
  thirdParty: [
    'urgence',
    'recruteur',
    'parrain',
    'parrainage',
    'enfant',
    'enfants',
    'conjoint',
    'parent',
    'ami',
    'collegue',
    'referent',
    'temoin',
    'tuteur',
  ],
  captionFiller: ['vos', 'votre', 'mes', 'mon', 'ma', 'n', 'no', 'optionnel', 'facultatif', 'obligatoire'],
  dates: {
    months: {
      jan: 1,
      fev: 2,
      mar: 3,
      avr: 4,
      mai: 5,
      juin: 6,
      juil: 7,
      aou: 8,
      sep: 9,
      oct: 10,
      nov: 11,
      dec: 12,
    },
    ongoing: ['en cours', 'présent', 'actuel', 'aujourd'],
  },
  sections: {
    work: {
      any: [
        'experience',
        'experiences',
        'experience professionnelle',
        'experiences professionnelles',
        'parcours professionnel',
        'emploi',
        'emplois',
        'historique professionnel',
        'postes occupes',
        'emplois precedents',
      ],
    },
    volunteer: {
      any: [
        'benevolat',
        'experience benevole',
        'experiences benevoles',
        'engagement associatif',
        'engagements associatifs',
        'vie associative',
        'experiences associatives',
      ],
    },
    education: {
      any: [
        'formation',
        'formations',
        'parcours scolaire',
        'parcours academique',
        'etudes',
        'diplome',
        'diplomes',
        'cursus',
        'scolarite',
        'parcours universitaire',
        'formation et diplomes',
        'formations et diplomes',
        'etudes et diplomes',
      ],
    },
    certificates: {
      any: ['certification', 'certifications', 'certificats', 'habilitations'],
    },
    awards: {
      any: ['prix', 'distinctions', 'prix et distinctions', 'recompenses'],
    },
    publications: {
      any: ['publications'],
    },
    skills: {
      any: ['competences', 'competence'],
    },
    languages: {
      any: ['langue', 'langues', 'langues etrangeres', 'competences linguistiques'],
    },
    interests: {
      any: ['centre d interet', 'centres d interet', 'loisirs', 'interets'],
    },
    references: {
      any: [
        'reference',
        'references',
        'references professionnelles',
        'recommandations',
        'personnes de reference',
      ],
    },
    projects: {
      any: ['projet', 'projets', 'projets personnels', 'realisations'],
    },
  },
  keys: {
    given_name: {
      any: ['prenom', 'prenoms'],
      not: ['nom du parent'],
    },
    family_name: {
      any: ['nom', 'nom de famille', 'nom d usage', 'patronyme'],
      not: [
        'prenom',
        'complet',
        'entreprise',
        'societe',
        'employeur',
        'poste',
        'fonction',
        'fichier',
        'ecole',
        'etablissement',
        'universite',
        'diplome',
        'utilisateur',
        'domaine',
        'rue',
        'ville',
        'contact d urgence',
        'recruteur',
      ],
    },
    full_name: {
      any: ['nom complet', 'nom et prenom', 'prenom et nom', 'votre nom et prenom', 'identite'],
      not: ['entreprise', 'societe'],
    },
    email: {
      any: [
        'email',
        'e mail',
        'mail',
        'courriel',
        'adresse email',
        'adresse e mail',
        'adresse mail',
        'adresse electronique',
        'courrier electronique',
      ],
      not: ['confirm', 'verifi', 'repet', 'nouveau', 'employeur', 'recruteur', 'parrain'],
    },
    email_confirm: {
      any: [
        'confirmer votre email',
        'confirmer email',
        'confirmation email',
        'confirmer e mail',
        'verifier email',
        'repeter email',
        'confirmez votre adresse',
      ],
      not: [],
    },
    phone: {
      any: [
        'telephone',
        'tel',
        'portable',
        'mobile',
        'numero de telephone',
        'no de telephone',
        'num telephone',
        'gsm',
      ],
      not: ['fixe du recruteur', 'entreprise', 'urgence'],
    },
    street: {
      any: ['adresse', 'adresse postale', 'rue', 'numero et rue', 'voie', 'complement d adresse'],
      not: ['mail', 'email', 'e mail', 'electronique', 'courriel', 'ip', 'url', 'site', 'linkedin', 'web'],
    },
    postal_code: {
      any: ['code postal', 'cp', 'zip'],
      not: [],
    },
    city: {
      any: ['ville', 'commune', 'localite', 'ville de residence', 'votre ville'],
      not: ['naissance', 'entreprise', 'societe', 'poste', 'ecole', 'universite', 'etablissement'],
    },
    country: {
      any: ['pays', 'pays de residence'],
      not: ['naissance', 'nationalite'],
    },
    linkedin_url: {
      any: ['linkedin', 'profil linkedin', 'url linkedin', 'lien linkedin'],
      not: [],
    },
    github_url: {
      any: ['github', 'gitlab'],
      not: [],
    },
    portfolio_url: {
      any: ['portfolio', 'site web', 'site internet', 'site personnel', 'votre site', 'book', 'page perso'],
      not: ['entreprise', 'societe', 'linkedin', 'github', 'offre'],
    },
    current_title: {
      any: [
        'poste actuel',
        'fonction actuelle',
        'intitule de votre poste',
        'votre poste actuel',
        'titre actuel',
        'emploi actuel',
        'votre fonction',
      ],
      not: ['recherche', 'souhaite', 'vise', 'postule', 'candidature', 'propose', 'a pourvoir'],
    },
    current_employer: {
      any: [
        'employeur actuel',
        'entreprise actuelle',
        'votre employeur',
        'societe actuelle',
        'entreprise actuelle ou derniere',
      ],
      not: ['recherche', 'souhaite', 'cible', 'postule'],
    },
    summary: {
      any: [
        'presentation',
        'a propos',
        'a propos de vous',
        'profil',
        'bio',
        'biographie',
        'resume de votre parcours',
        'quelques mots sur vous',
        'parlez nous de vous',
      ],
      not: [
        'carte',
        'photo',
        'carta',
        'lettre',
        'entreprise',
        'offre',
        'poste',
        'linkedin',
        'github',
        'url',
        'site',
        'lien',
      ],
    },
    cover_letter: {
      any: [
        'lettre de motivation',
        'motivation',
        'votre motivation',
        'message au recruteur',
        'message de candidature',
        'pourquoi ce poste',
        'pourquoi cette entreprise',
        'presentez votre candidature',
      ],
      not: ['fichier', 'joindre', 'telecharger', 'piece jointe', 'importer'],
    },
    years_experience: {
      any: [
        'annees d experience',
        'nombre d annees d experience',
        'experience en annees',
        'anciennete',
        'annees de pratique',
      ],
      not: [],
    },
    salary_expectation: {
      any: [
        'pretentions salariales',
        'pretention salariale',
        'salaire souhaite',
        'remuneration souhaitee',
        'salaire brut souhaite',
        'attentes salariales',
        'package souhaite',
      ],
      not: ['actuel', 'propose', 'offert', 'fourchette de l offre'],
    },
    notice_period: {
      any: ['preavis', 'duree de preavis', 'delai de preavis'],
      not: [],
    },
    availability_date: {
      any: [
        'disponibilite',
        'date de disponibilite',
        'disponible a partir de',
        'date d entree en poste',
        'des quand',
      ],
      not: [],
    },
    work_authorization: {
      any: [
        'autorisation de travail',
        'permis de travail',
        'titre de sejour',
        'droit de travailler',
        'autorise a travailler',
        'visa',
        'autorisation de travailler',
        'autorise a travailler en france',
        'droit de travail',
        'permis de travailler',
        'autorisation de travail en france',
      ],
      not: [],
    },
    education_degree: {
      any: [
        'diplome',
        'dernier diplome',
        'niveau d etudes',
        'niveau de formation',
        'formation',
        'intitule du diplome',
      ],
      not: ['ecole', 'etablissement', 'universite', 'annee'],
    },
    education_institution: {
      any: [
        'ecole',
        'etablissement',
        'universite',
        'nom de l ecole',
        'nom de l etablissement',
        'etablissement de formation',
      ],
      not: [],
    },
    skills: {
      any: ['competences', 'vos competences', 'competences cles', 'savoir faire'],
      not: ['obligatoire', 'requise', 'recherchee'],
    },
    languages: {
      any: ['langues', 'langues parlees', 'vos langues', 'niveau de langue'],
      not: ['programmation', 'informatique'],
    },
    'work.position': {
      any: [
        'poste',
        'intitule du poste',
        'intitule de poste',
        'titre du poste',
        'poste occupe',
        'fonction',
        'emploi',
        'metier',
        'intitule',
      ],
      not: [
        'date',
        'debut',
        'fin',
        'lieu',
        'ville',
        'description',
        'souhaite',
        'recherche',
        'vise',
        'entreprise',
        'societe',
        'employeur',
      ],
    },
    'work.company': {
      any: [
        'entreprise',
        'nom de l entreprise',
        'societe',
        'employeur',
        'nom de l employeur',
        'organisation',
        'structure',
        'raison sociale',
      ],
      not: [
        'date',
        'debut',
        'fin',
        'lieu',
        'ville',
        'description',
        'secteur',
        'taille',
        'effectif',
        'adresse',
        'telephone',
        'site',
      ],
    },
    'work.location': {
      any: ['ville', 'lieu', 'localisation', 'lieu de travail', 'ville de l entreprise'],
      not: ['naissance', 'date'],
    },
    'work.start': {
      any: ['date de debut', 'debut', 'date d entree', 'mois de debut', 'annee de debut', 'depuis'],
      not: ['fin'],
    },
    'work.end': {
      any: ['date de fin', 'fin', 'date de sortie', 'mois de fin', 'annee de fin', 'jusqu au', 'jusqu a'],
      not: ['debut'],
    },
    'work.description': {
      any: [
        'description',
        'description du poste',
        'missions',
        'vos missions',
        'principales missions',
        'description des missions',
        'taches',
        'responsabilites',
        'realisations',
      ],
      not: [],
    },
    'work.url': {
      any: ['site de l entreprise', 'site web de l entreprise'],
      not: [],
    },
    'volunteer.position': {
      any: ['role', 'fonction', 'poste', 'mission', 'intitule'],
      not: ['date', 'debut', 'fin', 'lieu', 'ville', 'description', 'association', 'organisme', 'structure'],
    },
    'volunteer.organization': {
      any: ['association', 'nom de l association', 'organisation', 'structure', 'organisme'],
      not: ['date', 'debut', 'fin', 'lieu', 'ville', 'description'],
    },
    'volunteer.start': {
      any: ['date de debut', 'debut', 'depuis'],
      not: ['fin'],
    },
    'volunteer.end': {
      any: ['date de fin', 'fin'],
      not: ['debut'],
    },
    'volunteer.description': {
      any: ['description', 'missions', 'actions', 'realisations'],
      not: [],
    },
    'education.degree': {
      any: [
        'diplome',
        'intitule du diplome',
        'diplome obtenu',
        'diplome prepare',
        'type de diplome',
        'niveau de diplome',
        'niveau d etudes',
        'formation',
        'intitule de la formation',
        'titre',
      ],
      not: [
        'date',
        'debut',
        'fin',
        'lieu',
        'ville',
        'description',
        'organisme',
        'ecole',
        'etablissement',
        'universite',
        'annee',
        'domaine',
        'specialite',
        'mention',
        'obtention',
      ],
    },
    'education.field': {
      any: ['domaine', 'domaine d etudes', 'specialite', 'filiere', 'discipline', 'majeure'],
      not: ['date', 'debut', 'fin'],
    },
    'education.institution': {
      any: [
        'ecole',
        'etablissement',
        'universite',
        'nom de l etablissement',
        'nom de l ecole',
        'organisme de formation',
      ],
      not: ['date', 'debut', 'fin', 'ville', 'adresse'],
    },
    'education.start': {
      any: ['date de debut', 'debut', 'annee de debut', 'date d entree', 'rentree'],
      not: ['fin', 'obtention'],
    },
    'education.end': {
      any: [
        'date de fin',
        'fin',
        'annee de fin',
        'annee d obtention',
        'date d obtention',
        'obtenu en',
        'annee du diplome',
      ],
      not: ['debut'],
    },
    'education.score': {
      any: ['mention', 'moyenne', 'note', 'resultat'],
      not: [],
    },
    'education.details': {
      any: ['description', 'details', 'cours', 'matieres', 'commentaire', 'informations complementaires'],
      not: [],
    },
    'certificates.name': {
      any: ['certification', 'nom de la certification', 'certificat', 'intitule', 'titre', 'nom'],
      not: ['date', 'organisme', 'emetteur', 'delivre', 'url', 'lien'],
    },
    'certificates.issuer': {
      any: ['organisme', 'organisme certificateur', 'delivre par', 'emetteur', 'autorite'],
      not: ['date'],
    },
    'certificates.date': {
      any: ['date', 'date d obtention', 'obtenu le', 'date de delivrance', 'annee'],
      not: ['expiration', 'validite'],
    },
    'certificates.url': {
      any: ['lien', 'url', 'lien de verification'],
      not: [],
    },
    'awards.title': {
      any: ['prix', 'distinction', 'titre', 'intitule', 'nom'],
      not: ['date', 'decerne', 'remis', 'organisme'],
    },
    'awards.awarder': {
      any: ['decerne par', 'remis par', 'organisme'],
      not: [],
    },
    'awards.date': {
      any: ['date', 'annee'],
      not: [],
    },
    'awards.description': {
      any: ['description', 'details'],
      not: [],
    },
    'publications.name': {
      any: ['titre', 'titre de la publication', 'intitule', 'nom'],
      not: ['date', 'editeur', 'revue', 'journal'],
    },
    'publications.publisher': {
      any: ['editeur', 'revue', 'journal', 'publie dans', 'publie par'],
      not: [],
    },
    'publications.date': {
      any: ['date', 'date de publication', 'annee'],
      not: [],
    },
    'publications.url': {
      any: ['lien', 'url', 'doi'],
      not: [],
    },
    'publications.description': {
      any: ['resume', 'description'],
      not: [],
    },
    'skills.name': {
      any: ['competence', 'nom de la competence', 'intitule', 'savoir faire'],
      not: ['niveau', 'maitrise'],
    },
    'skills.level': {
      any: ['niveau', 'niveau de maitrise', 'maitrise'],
      not: [],
    },
    'skills.keywords': {
      any: ['mots cles', 'outils', 'technologies'],
      not: [],
    },
    'languages.language': {
      any: ['langue', 'nom de la langue', 'langue parlee'],
      not: ['niveau', 'maitrise'],
    },
    'languages.fluency': {
      any: ['niveau', 'niveau de langue', 'niveau de maitrise', 'maitrise'],
      not: [],
    },
    'interests.name': {
      any: ['centre d interet', 'interet', 'loisir', 'activite'],
      not: [],
    },
    'interests.keywords': {
      any: ['details', 'mots cles'],
      not: [],
    },
    'references.name': {
      any: [
        'nom complet',
        'nom et prenom',
        'prenom et nom',
        'nom du referent',
        'nom de la personne',
        'identite',
      ],
      not: ['entreprise', 'societe', 'employeur'],
    },
    'references.reference': {
      any: ['recommandation', 'temoignage', 'citation'],
      not: [],
    },
    'projects.name': {
      any: ['projet', 'nom du projet', 'intitule', 'titre'],
      not: ['date', 'debut', 'fin', 'lieu', 'ville', 'description'],
    },
    'projects.description': {
      any: ['description', 'details', 'missions'],
      not: [],
    },
    'projects.start': {
      any: ['date de debut', 'debut'],
      not: ['fin'],
    },
    'projects.end': {
      any: ['date de fin', 'fin'],
      not: ['debut'],
    },
    'projects.url': {
      any: ['lien', 'url', 'lien du projet'],
      not: [],
    },
  },
};
